### ISSUE TITLE
XQuartz 2.8.0_rc2, x2go client 4.1.2.2, macOS Catalina 10.15.7 | x2go client can't open remote session

### ISSUE THREAD

**Issue by gfbi98** [XQuartz/XQuartz#113]
x2go client 4.1.2.2 was working perfectly XQuartz 2.7.11 in macOS Catalina 10.15.7

I have just updated to XQuartz 2.8.0_rc2 and now:

     1. Xquartz doesn't start automatically when I start x2go client program
     2. When I try to open an x2go remote session with x2go client, it seems to connect but immediately finishes the connection

**Comment by jeremyhu** [comment]
Did you logout?  Can you try rebooting?  Can you collect any error information to indicate what is happening and why?  Maybe grab a sysdiagnose?  Check Console.app, etc?

**Comment by SCarrSuperstar** [comment]
I just updated to XQuartz 2.8.0_rc2 on Catalina and X11 no longer works. Bummer! No error message reported.

**Comment by unelg** [comment]
> I just updated to XQuartz 2.8.0_rc2 on Catalina and X11 no longer works. Bummer! No error message reported.

same issue here. launching xterm from terminal app, the command sits and wait indefinitely. xterm -display :0 works. launching x apps via ssh fails without any errors, waits infinitely. (no help from -X -Y etc) because of problem with simple xterm command, I believe ssh is not faulty.

**Comment by jeremyhu** [comment]
@unelg From Terminal, what do you see with 'echo $DISPLAY'?  That sounds like an incorrect DISPLAY envvar.

**Comment by jeremyhu** [comment]
So is the issue here just that you had the wrong $DISPLAY set?

Did you logout after moving from 2.7.11 to 2.8.0?  The installer is supposed to force you to logout in that case.

Did the old 2.7.x LaunchAgent not get removed (check `ls /Library/LaunchAgents/*startx*`)?  The post-install script is supposed to remove it.

Did your aqua session not teardown with logout?  Check `launchctl getenv DISPLAY`.  It should include 'org.xquartz' with 2.8.0 and not 'org.macosforge.xquartz'.

Is DISPLAY in your Terminal not matching what launchd is setting?  Check `echo $DISPLAY` and compare with `launchctl getenv DISPLAY`.

---

I suspect this is the same as #102 and for some reason some folks aren't getting a fresh aqua session with the new LaunchAgent.
