### ISSUE TITLE
No libXp.6.dylib in XQuartz 2.8?

### ISSUE THREAD

**Issue by Youguang** [XQuartz/XQuartz#124]
After upgrade to XQuartz-2.8.0_rc3, I encounter this error: `dyld: Library not loaded: /opt/X11/lib/libXp.6.dylib`.

What can I do?

**Comment by dpeterc** [comment]
XQuartz 2.8.0_rc3 no longer contains libXp.6.dylib, and also removes any previous XQuartz installation during the upgrade.

Best long term solution is to fix your application, so that it no longer links to libXp
For example, if your application is Motif based, and your version of Motif library links to libXp, you recompile Motif with
`./configure --enable-xft --enable-jpeg --enable-png --disable-printing`
Last option will cause building of the Motif library without referencing libXp.
[libXp](https://www.x.org/archive/X11R6.8.1/doc/libXp.3.html) is an X11 extension for printing, which allows rendering of widgets to off-screen buffer for printing. It was an idea from 1990 which never took off, and I am not aware of any applications which use it. So it is highly unlikely that your application is using it.

But if it does, or you have an immediate support issues, and can not spend time building your software, you can remove XQuartz-2.8.0_rc3, install back XQaurtz-2.7.11, and then XQuartz-2.8.0_rc2, which keeps the libraries from the previous installations.

**Comment by jeremyhu** [comment]
If there are common libraries (like motif) that are linking libXp opportunistically, I can just re-add it, but I'll be sure to not include an arm64 slice.

**Comment by dpeterc** [comment]
Default Motif build does link to libXp, but it can be disabled, if you build your own.
If you would re-add libXp.6.dylib, it would probably help people, who are unable to compile it by themselves.

**Comment by dwcaress** [comment]
The OpenMotif package installed through Homebrew has the following in Xm.h:
    
#ifndef PRINTING_SUPPORTED
#define PRINTING_SUPPORTED 1
#endif

#ifdef PRINTING_SUPPORTED
#include <X11/extensions/Print.h>
#endif

Consequently, even if one does not link with libXp, building Motif code in this context requires the existence of /opt/X11/include/extensions/Print.h - this header disappeared along with libXp. Please also resurrect the related header files.

Our package MB-System
  https://www.mbari.org/products/research-software/mb-system/
  https://github.com/dwcaress/MB-System
depends on X11, OpenMotif, and OpenGL for it's graphical & visualization tools. On Macs the most common installation mode is through homebrew, with a dependence on an OpenMotif package that is built requiring libXp and the related headers.

**Comment by opoplawski** [comment]
FWIW - IDL still requires libXp so updating to 2.8.0 breaks that for us as well.

**Comment by jeremyhu** [comment]
I'm re-adding runtime support for all the legacy extensions on intel to support such cases.

**Comment by dwcaress** [comment]
Thank you. And I very much appreciate your updating XQuartz - it remains essential to enabling people to use our package on Macs.
One question - I infer from your comments that the legacy extensions at issue will not be present in XQuartz for Macs with M1 processors. Is this correct?
