### ISSUE TITLE
Font rendering is sub-optimal

### ISSUE THREAD

**Issue by xavier-bw** [XQuartz/XQuartz#147]
Hi,

I installed xquartz 2.8.0 but had to revert back to 2.7.11 because the courier font I use for coding became much harder to read, and whatever other fonts I tried were no better.

If you take a look at the examples below, there are a lot of small changes, not sure what it is that breaks readability for me, but the lines on b/p/P/F that are no longer lines, the s that's no longer balanced, are perhaps the things that make me feel text is no longer in focus and make it an effort to read.  Not sure if other people get the same feeling... a small example such as this is perhaps not a problem, but looking at longer blocks of text was.

![2 7 11](https://user-images.githubusercontent.com/80335274/113406969-b2e5e180-93ac-11eb-983c-48f79e7dfaf0.png)

![2 8 0](https://user-images.githubusercontent.com/80335274/113406870-83cf7000-93ac-11eb-8f9f-2bb090119f8a.png)

is there settings that can make this look better?

Thanks,

Xavier

**Comment by dpeterc** [comment]
Hello Xavier,

It is a poor consolation, but fonts on Linux are just as broken.
See the comparison of your sample and X.Org 1.19.6 on SuSE Linux 15.0.
It even has asymmetrical 0. And the funny one pixel gap on F and P.
It becomes much more useful with XFT antialiasing.
![FontXqaurtzCompound](https://user-images.githubusercontent.com/15419249/113458404-692fe200-9412-11eb-814d-91e50868a003.png)
My guess is that there is nothing wrong with XQuartz, but that simply font rendering in X.Org has changed.
Most fonts nowadays are vector based, not hand drawn as they used to be.
They use various (patented) hinted algorithms so that it looks good on small pixel sizes.
And people care much more about high resolution antialiased rendering, not so much about low resolution bilelvel font rendering. So it is quite possible that font rendering is improved in one use case, and made worse in another.

Here is some more information about the complexities of font rendering on various platforms.
https://pandasauce.org/post/linux-fonts/

**Comment by jeremyhu** [comment]
This is probably related to taking a newer version of freetype and has nothing to do with the server itself.

**Comment by WorkDayHeyHey** [comment]
I don't thing it Linux's problem. I can export the same applications out unto Linux and Widows X with none of this.

**Comment by jeremyhu** [comment]
Not actionable.  If you can identify what the issue is (ie: a change in freetype), feel free to reopen and let me know...
