### ISSUE TITLE
Assertion failure (!xcb_xlib_extra_reply_data_left) in 2.8.0

### ISSUE THREAD

**Issue by fratomtom** [XQuartz/XQuartz#150]
Dear All,

I am writing due to issues aroused after upgrading to XQuartz 2.8.0 (I am running on Mac OS 10.14.6). I am using some codes producing graphics that are visualised with XQuartz, and I had no issue until the upgrade.

I get the following error messages:

**[xcb] Extra reply data still left in queue
[xcb] This is most likely caused by a broken X extension library
[xcb] Aborting, sorry about that.
Assertion failed: (!xcb_xlib_extra_reply_data_left), function _XReply, file xcb_io.c, line 665.
Abort trap: 6**

Do you have any hint? I also tried to move back to 2.7.11, but apparently this is not fixing the issue (I got no error messages, but XQuartz gets stucked).

Thanks for your support.

Best regards

**Comment by jeremyhu** [comment]
To move back to 2.7.11, you need to first fully uninstall 2.8.0 (and you need to reboot afterwards).  See https://www.xquartz.org/FAQs.html for more specifics.

However, can you please first help determine if your issue is with changes in the server or client side libraries?  To do this, please:


1. Install 2.7.11
2. Rename /Applications/Utilities/XQuartz.app to XQuartz-2.7.11.app
3. Install 2.8.0
4. Reboot
5. Launch XQuartz-2.7.11.app and then from its xterm, run your application.

If that fails, it means the issue is client side.

If that succeeds, it means the issue is server side.

Can you give me steps to reproduce the problem?

**Comment by jeremyhu** [comment]
And to be completely verbose, can you please try 2.8.1_beta1 as it moves to a different server branch (1.20 compared to 1.19 in 2.8.0).  Thanks.

**Comment by fratomtom** [comment]
Hi, I tried following the steps you proposed, but it did not succeed in solving the issue.
The software I am running only works when downgrading to XQuartz 2.7.11.

**Comment by jeremyhu** [comment]
So are you saying that you are still seeing this issue when you use the XQuartz-2.7.11 server with the updated userland dylibs from 2.8.0?

Can you provide steps to reproduce?

**Comment by jeremyhu** [comment]
Can you also please attach your full crash log?

**Comment by fratomtom** [comment]
Hi,
I followed exactly the steps that you suggested, at point 5 I open the XQuartz 2.7.11 terminal and launched my application, but it crashed again. The full error message I got is the one I reported in my first message, unfortunately I do not get further output.
Best

**Comment by jeremyhu** [comment]
Thanks.  That means it's not a bug in the server.  It's eitehr a bug in libX11, libxcb, or your application (which is being revealed by hardening in the libraries).  Looking around at similar issues on the internet, it seems most likely to be the latter.

What is the application?  Is there a way I can reproduce this?

When your application crashes, you should get a crash log saved to ~/Library/Logs/DiagnosticReports.  Please look for it and attach it.  Thanks.

**Comment by jeremyhu** [comment]
It sounds like this is probably just catching a bug in your app with new checks in client libraries.  Please report the issue to your app's maintainer.
