### ISSUE TITLE
Support for M1 Mac?

### ISSUE THREAD

**Issue by YunxuanSong** [XQuartz/XQuartz#19]
Hi all
The Apple released the new Mac version with M1.
 Did XQuartz work on it ?

**Comment by hexagonal-sun** [comment]
I've been using XQuartz on an M1 Mac (with Rosetta translation) with no issues for a few days now if that helps.

**Comment by larb0b** [comment]
It seems the arm64 build of xorg-server in MacPorts is building OK, might want to grab X from there.

https://ports.macports.org/port/xorg-server/summary

**Comment by securingmom** [comment]
The XQuarts on the site is a bit dated? 2016
https://www.xquartz.org/

Ought M1 users (MacBook Pro 16" i9?) use a more recent version?  Is that here on github?  as a release?

**Comment by YunxuanSong** [comment]
Did it work in HomeBrew as I am a HomeBrew fans.？

**Comment by jinyl777** [comment]
@hexagonal-sun  hellow can I ssh -Y to ubuntu and open ide in m1 mac?

**Comment by bpottier** [comment]
Any reason this was closed? I know mac ports has an option that builds but I much prefer to run homebrew.

**Comment by jeremyhu** [comment]
I hope to have an alpha package availble soon.  The build script I added to the repo produces a full arm64+x86_64 build of XQuartz using newer (although not necessarilary latest) versions of component projects.  It drops i386 support, drops deprecated bincompat libraries, is missing some documentation, doesn't have a separate dSYMS tarball produced, and doesn't notarize the resulting dmg (mainly because of some issues I'm having submitting for notarization).

So it's "fixed" in that you can run compile.sh to build it yourself, but if you want an actual release, it'll be a little while.

**Comment by securingmom** [comment]
> if you want an actual release, it'll be a little while.

BIG hug.  🤗
