### ISSUE TITLE
Can't open XQuartz 2.80 or 2.8.1 on M1 Mac Big Sur

### ISSUE THREAD

**Issue by cbarkachi** [XQuartz/XQuartz#202]
After downloading and opening, I encounter the following logs:

Process:               X11.bin [791]
Path:                  /Applications/Utilities/XQuartz.app/Contents/MacOS/X11
Identifier:            org.xquartz.X11
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        ??? [1]
Responsible:           X11.bin [791]
User ID:               501

Date/Time:             2021-09-06 02:34:25.022 -0400
OS Version:            macOS 11.2.3 (20D91)
Report Version:        12
Anonymous UUID:        63378331-A3B0-48BE-1710-D4FB28517D7C

Time Awake Since Boot: 560 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: 30E6CA21-D5E6-36F7-8CF2-AABA2D292564
Library not loaded: /opt/X11/*/libAppleWM.7.dylib
  Referenced from: /Applications/Utilities/XQuartz.app/Contents/MacOS/X11.bin
  Reason: no suitable image found.  Did find:
	/opt/X11/*/libAppleWM.7.dylib: stat() failed with errno=13

Binary Images:
       0x104534000 -        0x1046abfff +X11.bin (0) <C9723ACE-8073-3B35-B404-8A4801EB02F1> /Applications/Utilities/XQuartz.app/Contents/MacOS/X11.bin
       0x104794000 -        0x1047e7fff +org.sparkle-project.Sparkle (1.26.0 - 1.26.0) <C378FD36-88AA-3A10-9865-BCDC7EC3863B> /Applications/Utilities/XQuartz.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x104a78000 -        0x104af3fff  dyld (832.7.3) <4AB185B3-DC20-3C03-A193-67C0E6C589D7> /usr/lib/dyld
       0x184856000 -        0x184e7bfff  com.apple.audio.CoreAudio (5.0 - 5.0) <2A4CD49F-AB5D-3155-9889-2A388B4505DE> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
       0x1857bf000 -        0x185889fff  com.apple.framework.IOKit (2.0.2 - 1845.81.1) <516911DA-18D7-3D17-8646-BBF7C75CD070> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
       0x196c47000 -        0x196c4afff  com.apple.Cocoa (6.11 - 23) <4FD56058-DC7C-3FDF-9305-12D435FF95AD> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
       0x19ecd5000 -        0x19ecd8fff  com.apple.Carbon (160 - 164) <7DE1820C-F271-3AAD-B1CC-A04F147A8EAA> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
       0x1c58c6000 -        0x1c58d5fff  com.apple.opengl (18.1.1 - 18.1.1) <3172E66B-6B24-3178-8E0C-90D49EBD5C24> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
       0x1d423f000 -        0x1d424efff  libXplugin.1.dylib (47) <E60FF4F1-7609-3BBF-9A95-B14A79AE31F7> /usr/lib/libXplugin.1.dylib

**Comment by jeremyhu** [comment]
13 is EACCES ... can you debug this to find out what is wrong with that file (/opt/X11//libAppleWM.7.dylib)?  What are its permissions on disk?  Are you able to open it (eg, run `file /opt/X11//libAppleWM.7.dylib`)?

**Comment by markyashar** [comment]
I'm encountering a similar issue. When I download and try to launch XQuartz 2.8.1 on macOS Big Sur Version 11.6.1 (Chip Apple M1), I get the following error message (note that I don't have admin access to this Mac): 

Code Type:             ARM-64 (Native)
Parent Process:        ??? [1]
Responsible:           X11.bin [43596]
User ID:               2105117206

Date/Time:             2021-12-14 23:55:19.071 -0800
OS Version:            macOS 11.6.1 (20G224)
Report Version:        12
Anonymous UUID:        9CAC97CE-6FFD-F714-058E-19436E8D8F33

Sleep/Wake UUID:       C7308829-817A-43E8-A3C6-69259CEBF0E9

Time Awake Since Boot: 63000 seconds
Time Since Wake:       6900 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: 4D8A7BB1-6AEE-3EB1-A96A-2825C6CFBB8A
Library not loaded: /opt/X11/*/libAppleWM.7.dylib
  Referenced from: /Users/USER/*/XQuartz.app/Contents/MacOS/X11.bin
  Reason: image not found

Binary Images:
       0x1040c0000 -        0x104237fff +X11.bin (0) <C9723ACE-8073-3B35-B404-8A4801EB02F1> /Users/USER/*/XQuartz.app/Contents/MacOS/X11.bin
       0x104308000 -        0x104387fff  dyld (852.2) <CBE63EFC-4577-3CDA-8A86-0FECB1E398A8> /usr/lib/dyld
       0x104410000 -        0x104463fff +org.sparkle-project.Sparkle (1.26.0 - 1.26.0) <C378FD36-88AA-3A10-9865-BCDC7EC3863B> /Users/USER/*/XQuartz.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x195e83000 -        0x19649dfff  com.apple.audio.CoreAudio (5.0 - 5.0) <695F9E3E-FDEF-3251-B363-81C77B18B41B> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
       0x196dee000 -        0x196eb9fff  com.apple.framework.IOKit (2.0.2 - 1845.120.6) <887D0A8C-A901-336D-BEF5-C2DAEFEC78A4> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
       0x1a8585000 -        0x1a8588fff  com.apple.Cocoa (6.11 - 23) <68ACE089-83D1-33A7-8607-91D00AD1C27A> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
       0x1afe3f000 -        0x1afe42fff  com.apple.Carbon (160 - 164) <E0FFEC42-4283-3AA5-92C1-FE6FE535F3C5> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
       0x1d6726000 -        0x1d6735fff  com.apple.opengl (18.5.9 - 18.5.9) <00D78BCB-F358-3B73-B9DE-8F6938C04BD8> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
       0x1e7cee000 -        0x1e7cfdfff  libXplugin.1.dylib (47) <C0563D24-2691-38FD-8697-8F7C85EF7ACA> /usr/lib/libXplugin.1.dylib

Model: MacBookPro17,1, BootROM 7429.41.5, proc 8:4:4 processors, 16 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: LPDDR4
AirPort: spairport_wireless_card_type_airport_extreme, wl0: Aug 18 2021 22:48:53 version 18.50.40.11.7.8.123 FWID 01-3ed0e3a2
Bluetooth: Version 8.0.5d7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: USB 3.1 Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by raoultrines** [comment]
In the above message, I spot two paths that look strange to me:

Library not loaded: /opt/X11//libAppleWM.7.dylib
Referenced from: /Users/USER//XQuartz.app/Contents/MacOS/X11.bin

Note the double slashes (//) in both. Something is definitely rotten in the state of the library paths. That's where I would start looking.

**Comment by jeremyhu** [comment]
Closing due to lack of response to my questions above.
