### ISSUE TITLE
XQuartz 2.8.1 M1 mac mini black screen issue

### ISSUE THREAD

**Issue by azfalcon** [XQuartz/XQuartz#211]
Running XQuartz 2.8.1 M1 mac mini client to display IntelliJ 2021.2.1 Java IDE from Ubuntu 20 using 'IntelliJ Light' (default) mode cases the display to turn black when the window has focus making it unusable. When focus is moved to another MacOS widow the IntelliJ window displays normally. Works perfectly well on Intel based Mac rinning XQuartz 2.8.1 and Big Sur. The problem is only visible on M1 based Mac.

**Comment by raoultrines** [comment]
There are several issues that may be related: #31, #195 and #200.

**Comment by azfalcon** [comment]
Thank you - yep, looks very much like these. I have had to send my M1 Mac mini back to Apple and am replacing it with an Intel based model.

**Comment by marigonda** [comment]
I encountered this issue today with my new Mac Mini. After some investigation, I discovered that the problem was related to Java applications. For me, the following solution worked:

-Dsun.java2d.xrender=false

For PyCharm, I added this line to:

~/.config/JetBrains/PyCharm<VERSION>/pycharm64.vmoptions

I hope this helps someone else!
