### ISSUE TITLE
Black background using XQuarts with IGV from remote server

### ISSUE THREAD

**Issue by tbrittoborges** [XQuartz/XQuartz#220]
I use XQuartz to use a remote application called [IGV](https://software.broadinstitute.org/software/igv/). In macOS Big Sur (11.6), with the M1 chip with 2 screens, I experience the application runs with a black background if the application is in the foreground, but a white background, if the application is in the background:

A few more details:
- My background is not black
- It's not running in dark mode
- The problem persists if mirror the laptop screen
- I tried to change the `Output/full-screen mode` setting and other settings, to no avail
 

<details><summary> System Overview:</summary>

      System Version: macOS 11.6 (20G165)   
      Kernel Version: Darwin 20.6.0   
      Time since boot: 1:07   
      Model Name: MacBook Air   
      Model Identifier: MacBookAir10,1   
      Chip: Apple M1   
      Total Number of Cores: 8 (4 performance and 4 efficiency)   
      Memory: 16 GB   
      System Firmware Version: 6723.140.2   
      OS Loader Version: 6723.140.2   

</details>

<details><summary> Software Version:</summary>

  Local:
  XQuartz 2.8.1 (xorg-server 1.20.11) installed with brew 
  Remote:  
  openjdk version "11.0.2" 2019-01-15  
  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.2+9)  
  OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.2+9, mixed mode)  
  WARN [2021-10-29T09:36:40,905]  [Globals.java:138] [AWT-EventQueue-0]  Development mode is enabled  
  INFO [2021-10-29T09:36:41,082]  [Main.java:156] [AWT-EventQueue-0]  Startup  IGV Version 2.5.3 05/29/2019 10:59 AM  
  INFO [2021-10-29T09:36:41,108]  [Main.java:157] [AWT-EventQueue-0]  Java 11.0.2 (build 11.0.2+9) 2019-01-15  
  INFO [2021-10-29T09:36:41,109]  [Main.java:160] [AWT-EventQueue-0]  Java Vendor: AdoptOpenJDK  https://adoptopenjdk.net/  
  INFO [2021-10-29T09:36:41,111]  [Main.java:162] [AWT-EventQueue-0]  JVM: OpenJDK 64-Bit Server VM AdoptOpenJDK  
  INFO [2021-10-29T09:36:41,347]  [Main.java:166] [AWT-EventQueue-0]  OS: Linux 4.19.0-17-amd64 amd64  

</details>

Others have reported this issue:
https://apple.stackexchange.com/questions/428589/xquartz-has-a-black-background-with-all-apps?newreg=a43926a430064713af1b10484cfe8c95

**Comment by raoultrines** [comment]
Same as #31 ?

**Comment by christophercrary** [comment]
Same here, on XQuartz 2.8.1 and Apple Silicon.

<details><summary>System Overview</summary>

```
Model Name: MacBook Pro
Model Identifier: MacBookPro18,2
Chip: Apple M1 Max
Total Number of Cores:	10 (8 performance and 2 efficiency)
Memory: 32 GB
System Firmware Version: 7429.30.65
OS Loader Version: 7429.30.65
```
</details>


The first of the following two images shows an example of the problem. The program Quartus is getting forwarded through XQuartz, and the main window in the background is colored appropriately, but the sub-windows that are in the foreground are colored inappropriately.

What's even more wild about the problem is that a screenshot of the messed-up windows appears differently when I view the image in different programs... Refer to the second image.


![xquartz_black_background_bug](https://user-images.githubusercontent.com/17283297/141689989-398bd03b-a78b-47a8-9fb5-e5c0bde608c9.jpeg)


![xquartz_black_background_bug](https://user-images.githubusercontent.com/17283297/141689790-3abb6daf-9416-43c2-ae76-086082d3b3a0.png)
