### ISSUE TITLE
No matching fbConfigs or Visuals found - failed to load driver: swrast

### ISSUE THREAD

**Issue by kmiklas** [XQuartz/XQuartz#231]
Attempting to run Chrome ``google-chrome`` v96.0.4664.45 from an AWS EC2 Ubuntu 20.04 instance, and redirect display to my Mac, Intel Chip, Big Sur, xquartz v2.8.1.

Why am I getting the errors below?

The application launches, but is painfully slow; I can't type a URL into the search bar. xeyes, xclock, and xcalc all work.

UBUNTU:

    sudo cat /etc/ssh/sshd_config | grep X11
    X11Forwarding yes
    X11DisplayOffset 10
    X11UseLocalhost yes

ERROR
    $ google-chrome
    libGL error: No matching fbConfigs or visuals found
    libGL error: failed to load driver: swrast

MACBOOK

- X11 server (xquartz) installed
- Connection command:
    ``ssh -X -i qwerty.pem ubuntu@192.0.2.0``

REFERENCES

1. https://unix.stackexchange.com/questions/12755/how-to-forward-x-over-ssh-to-run-graphics-applications-remotely

**Comment by quantumsheep** [comment]
Discussed in #144.

**Comment by quantumsheep** [comment]
You can try setting `LIBGL_ALWAYS_INDIRECT` environment variable to `1` on the target.
```
export LIBGL_ALWAYS_INDIRECT=1
```

**Comment by huntekye** [comment]
I've been running into some similar problems, first on macOS 11.6, and now on 12.0.1 (MacBook Pro, Intel processors), with XQuartz 2.8.1. On macOS 11.6 I could connect via `ssh -X`, and `xeyes` worked remotely, for example, but `glxgears` would not open at all. 

Now on macOS 12.0.1, `ssh -X` no longer works, giving the error 
`Warning: untrusted X11 forwarding setup failed: xauth key data not generated`
on login. `ssh -Y` successfully generates fake data it seems, and xeyes will work (this stuff about authentication probably isn't relevant to the problem, but the change after updating the OS seemed worth mentioning.)

So for the heart of the problem, running `LIBGL_DEBUG=verbose  glxgears` opens an X window with gears, but they don't move, and outputs:
```
libGL: OpenDriver: trying /usr/lib64/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /usr/lib64/dri/swrast_dri.so
libGL: Can't open configuration file /home/chem/huntekye/.drirc: No such file or directory.
libGL: Can't open configuration file /home/chem/huntekye/.drirc: No such file or directory.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
35493 frames in 8.2 seconds = 4304.769 FPS
```
And when I end the process:
```
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server "localhost:11.0"
      after 72342 requests (44 known processed) with 0 events remaining.
```

Taking quantumsheep's advice and running `LIBGL_DEBUG=verbose LIBGL_ALWAYS_INDIRECT=1 glxgears` will open another window with static gears, but now only outputs:
```
25013 frames in 5.1 seconds = 4925.290 FPS
```
And when the window is closed:
```
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server "localhost:11.0"
      after 51276 requests (37 known processed) with 0 events remaining.
```

At this point I'm fairly confused since the library and driver errors do go away, but the gears still won't budge. Hopefully this info will help, thanks.

**Comment by rdzman** [comment]
Possibly related to (duplicate?) #144.

**Comment by pprindeville** [comment]
@jeremyhu Given that this has come up as two different issues and not been resolved, can we reopen and assign this please?

**Comment by robertlagrant** [comment]
I've had this same issue today, on XQuartz 2.8.5, X-Server 21.1.6. MacOS Sequoia 15.2, M1 Pro.
