### ISSUE TITLE
XQuarzt 2.8.1 and cluster issues (FSL)

### ISSUE THREAD

**Issue by rossella64** [XQuartz/XQuartz#243]
Hi everyone, 

I am trying to open a program (FSL) on a cluster ssh. Whenever I run "fsleyes", I get the following error. 

The program 'fsleyes' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadCurrentWindow'.
  (Details: serial 7274 error_code 166 request_code 149 minor_code 5)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

I already tried the **defaults write org.macosforge.xquartz.X11 enable_iglx -bool true** but it didn't help. 
Also I installed an older version of XQuartz, but that didn't help either.
Does anyone have any suggestions? Would be very grateful!

**Comment by raoultrines** [comment]
You should also make sure that the X11 server on the Mac is started with the flag +iglx enabled; this is disabled by default. You can do this via changing the line `defaultserverargs=""` to `defaultserverargs="+iglx"` in the file `/opt/X11/bin/startx`. Then kill and restart the X11 server (XQuartz app).

Personally, I don't like OpenGL/GLX over SSH (indirect GLX) very much, since it is so hard to make it work. When I can, I use a virtual server (like VNC), so all the GLX rendering is done on the remote machine, and I only need to make it work there. This saves me a lot of hassle with uncooperative Macs or Windows machines, and I don't have to worry about overheating my Mac laptop either. (Hardware acceleration is hard work and produces a lot of heat. A remote Linux server usually has much better cooling than my local Mac laptop.)

**Comment by jeremyhu** [comment]
#144
