### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by Wongboo** [XQuartz/XQuartz#252]
Not sure the issue may be duplicate, Here is my screenshot of terminal and xquartz terminal, Clearly latter have font issue.
<img width="977" alt="截屏2022-03-16 22 51 56" src="https://user-images.githubusercontent.com/44860323/158618731-ad77046b-685f-4565-aa2d-6a25e064c9d9.png">
<img width="512" alt="截屏2022-03-16 22 52 04" src="https://user-images.githubusercontent.com/44860323/158618818-40799905-cb50-416a-934e-288dd7153670.png">

**Comment by jeremyhu** [comment]
You need to choose the font you want in xterm.  Your chosen font does not select that.

**Comment by benz0li** [comment]
I am running

* macOS 13.5.2 22G91 arm64
* XQuartz 2.8.5
* zsh 5.9
    * Framework: [Oh My Zsh](https://github.com/ohmyzsh/ohmyzsh)
    * Theme: [Powerlevel10k](https://github.com/romkatv/powerlevel10k)
    * Font: [MesloLGS NF](https://github.com/romkatv/powerlevel10k-media)

@Wongboo: In my case, executing `xterm -en UTF-8 -fa "MesloLGS NF"` did the trick.

---

In order to persist `-en UTF-8` and `-fa "MesloLGS NF"` for XQuartz:

1. Execute `defaults write org.xquartz.X11 "app_to_run" "/opt/X11/bin/xterm -en UTF-8"`.
    * This overrides the default `"app_to_run" "/opt/X11/bin/xterm"`
2. Create file `~/.Xresources` with the following content:  
    ```
    xterm*faceName: MesloLGS NF
    ```

When starting XQuartz now, you get the same result.

---

<img width="496" alt="XQuartz Font" src="https://github.com/XQuartz/XQuartz/assets/20233085/56186129-4252-4de2-9dac-93532cf09cef">
