### ISSUE TITLE
Installation queries for autoupdate or fail.

### ISSUE THREAD

**Issue by MichaelTiernan** [XQuartz/XQuartz#268]
When attempting an upgrade, I got a window asking me to authenticate/authorize for autoupdate. No alternative seems to be allowed. (Preventing update.)

### Hardware is:
```
Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,3
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	3.1 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  System Firmware Version:	451.120.7.0.0
  OS Loader Version:	540.120.3~6
  SMC Version (system):	2.45f5
```

### And the OS is:

```
System Software Overview:

  System Version:	macOS 12.4 (21F79)
  Kernel Version:	Darwin 21.5.0
  Boot Volume:	Brain
  Boot Mode:	Normal
[...]
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	16:19
```

## Screen shots if it helps:

To start with:
<img width="396" alt="image" src="https://user-images.githubusercontent.com/7912879/177326642-f18e47e8-7da1-45ba-9b0b-f7e177412db3.png">

It reports the update available:
<img width="732" alt="image" src="https://user-images.githubusercontent.com/7912879/177326761-5e90794e-1515-4959-ba7d-884559f5dc3e.png">

And takes me to the relaunch point:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/7912879/177326861-0c280acb-33d0-47af-8b02-8c221c12126f.png">

It then gives me this screen:
<img width="370" alt="Screen Shot 2022-07-05 at 8 15 30 AM" src="https://user-images.githubusercontent.com/7912879/177326931-40e2ea8c-10ec-4234-bc56-3e14a1d2e6c5.png">

Which seems to indicate that I can't install it without allowing "Auto update" which is not an option of any kind for me.

### What I expected:
I would expect that I'm given a choice *"Do you wish to enable 'autoupdate'?"* which I then can decline if I want but it won't stand in the way of installing the package.

Thanks to all!

**Comment by ykh-siteimprove** [comment]
The same state, but "Updating XQuartz" shows: "Installing Update" for 24+h

**Comment by jeremyhu** [comment]
@MichaelTiernan What do you mean by "which is not an option of any kind for me"?  Do you mean you don't have admin access to your machine, so you cannot apply the update?  If so, just click the "Skip this version" button, and you won't get prompted again...

> which I then can decline if I want but it won't stand in the way of installing the package.

Huh?  Do you want to install the update or not?  I'm confused.  If you want to install the update, then provide your password, so the package can be installed.

---

@ykh-siteimprove Your issue seems completely unrelated to what is reported here.  Your install seems stuck for some reason.  You should take a sysdiagnose pointed at the stuck process (eg: 11408 or perhaps installd) and send a bug to Apple (http://feedback.apple.com) with that sysdiagnose attached.  Report the FB # here if you want me to help push on it.

**Comment by ykh-siteimprove** [comment]
@jeremyhu No, thanks. I downloaded dmg and successfully installed new version

**Comment by jeremyhu** [comment]
> Yes. I am seeking to install the update but am not accepting a forced "Autoupdate" option.

It's not forced.  You have the option of disabling it...
