### ISSUE TITLE
error when drawing borders in motif

### ISSUE THREAD

**Issue by An8drew** [XQuartz/XQuartz#307]
Borders around various objects are not being drawn correctly. I've tested this with 2.8.4 and 2.8.5_beta1.
I've attached a very simple program which exemplifies the issue. To compile:

cc -L/opt/homebrew/lib -I/opt/homebrew/include -o testborder testborder.c -lXm -lXt -lX11

To run:

./testborder

A popupwindow with a radiobox will be created. The border for the radiobox will be drawn incorrectly.

Commenting out the following line in the program (line 37)

XtSetArg(args[ac], XmNdefaultPosition, False); ac++;

fixes the border problem, but the window position is not correct.

I am running MacOS 12.6 with the M1 chip

[testborder.zip](https://github.com/XQuartz/XQuartz/files/10311503/testborder.zip)

**Comment by dpeterc** [comment]
I have reproduced this bug, and found even easier way to reproduce it.
Bug is not inherently related to Motif, but to drawing to windows with position other than default.
It probably happens in all toolkits, which allow this functionality. 

The simplest reproducer with just programs shipped with XQuartz is by using xmessage.
If we call from command line it with
`xmessage "Is okay button rendered correctly"`
but if we call it with -center option like this
`xmessage -center "Is okay button rendered correctly"`
then the drawing of box and button is missing, see the picture below:
![image](https://user-images.githubusercontent.com/15419249/209884889-97ef0327-ed66-4357-9da9-fb0e1478c368.png)
The missing rectangles are permanent - if you move the window or resize it, in order to force a redraw, it continues to miss some user interface parts.

Bug is not related to Intel or M1 version of CPU, or to version of  MacOS; it is related o version of XQuartz.
Last good version was XQuartz 2.8.2
Bug has started to occur with XQaurtz 2.8.3beta1 (22.july.2022) and continues into 2.8.3, 2.8.4 and current last 2.8.5beta1
I presume that the drawing is happening, but with wrong offset, since Xlib internally uses wrong x,y offset of the moved window during the Xlib drawing operations.

**Comment by dpeterc** [comment]
Another way to see the bug is to set window initial position using standard X11 -geometry options.
Calling xmessage with the following parameter
`xmessage -geometry +20+20 tralala`
gives this picture
![image](https://user-images.githubusercontent.com/15419249/209941833-04f740a3-b24e-4edd-86de-ce9698cefeba.png)
where the borders of buttons and rectangles are partially clipped, depending on the size of geometry offset parameter.
If the window is resized, clipping adjusts proportionally and remains active.
Same bug can also be obtained by setting -geometry offset with other standard X11 clients like xman, xedit, xfontsel.

**Comment by jeremyhu** [comment]
The good news is that it looks like the changes I was working on this past week address this ... at least the `xmessage "Is okay button rendered correctly"` and `xmessage -geometry +20+20 tralala` cases worked fine for me.  I should have something for you to try with 2.8.5_beta3 hopefully later this week or next.

**Comment by dpeterc** [comment]
Thank you, looking forward to trying it out, once the update is released.
This bug prompted me to implement window placement settings, although frown upon from UI purist's design point of view, it is surprisingly popular with (OCD) users :-)

**Comment by dpeterc** [comment]
Thanks, I confirm the issue has been solved.
