### ISSUE TITLE
Applications -> Customize becomes unusable

### ISSUE THREAD

**Issue by yesyves** [XQuartz/XQuartz#32]
Hi

I'm using current Macports X11 (xorg-server 1.20.10 / quartz-wm 1.3.2) on BigSur (11.1) and the Customize Applications list window always work on X11 startup but becomes unusable after a while : 

- The blue line over selected items becomes black and opaque
- Selecting another item does not work
- Double-clicking an item makes the texte become invisible although it is still possible to write in it

I would love to have reproducible steps to give you, especially that it now seems to be running very fine today ! The one thing that may have changed is that I removed default Xlogo and Xman from the menu ...

Thanks !

**Comment by jeremyhu** [comment]
Oh, I'm able to move the issue.  Doing that instead.

**Comment by tglsfdc** [comment]
I'm also seeing misbehavior of the Customize dialog in 2.8.0_beta1 on Big Sur 11.1.  It might not be the same as described here though, because I'm not using dark mode.  I tried to add an item by clicking "Add Item", and what I got was a blank entry that there seemed no way to edit, nor could I remove it.

... but a few minutes later, while composing this note, I tried again and it worked just fine.  I hadn't restarted XQuartz or anything, so I'm baffled what changed.
