### ISSUE TITLE
Installation of XQuartz 2.8.5 fails without a meaningful error message

### ISSUE THREAD

**Issue by dpeterc** [XQuartz/XQuartz#322]
I was installing XQuartz 2.8.5 remotely to a customer with M1 processor with Ventura 13.1, but it failed with the following message.
![DSC_8895](https://user-images.githubusercontent.com/15419249/215908514-2d205f88-0837-4a64-b25c-2bcaba828939.jpg)
Previously they had XQuartz 2.8.1 and it worked.
I have tried 2.8.4 with same results, then I gave us and restored the working 2.8.1
How can I get a more meaningful message, which would help in debugging the problem?

**Comment by jeremyhu** [comment]
You can look in /var/log/install.log (or provide it here) to see what the error was

**Comment by gernophil** [comment]
This issue was closed without
 any solution. I have the same problem with the .pkg installer. I can successfully install via commandline: `$ sudo installer -pkg XQuartz-2.8.5.pkg -target /`. However I can't install via GUI. I've attached an error.log (unfortunately, it's in German).

[error.log](https://github.com/XQuartz/XQuartz/files/10872097/error.log)
