### ISSUE TITLE
Xephyr binary

### ISSUE THREAD

**Issue by larb0b** [XQuartz/XQuartz#33]
How is the Xephyr binary actually built? I'm assuming there are some patches and etc. used internally but the repository only seems to have a prebuilt binary (an x86-64 only one at that).

**Comment by jeremyhu** [comment]
It was built a long time ago from an older version of xorg-server (specifically 1.6.5-apple3).  There were issues with newer builds of it even from the same old sources (against newer libraries).  We ended up just shipping the older binary due to it being EOL and not a prioority.

I feel like maybe we identified the issue and fixed it in Xnest and xf86-video-nested but never got around to Xephyr... but I might be thinking of something else related to XKB.  This was about a decade ago, so the details are fuzzy to me.

I guess we should probably just try building it, seeing what breaks, and start with first principals.

**Comment by jeremyhu** [comment]
So I just build Xephyr with current sources (switched --disable-xephyr to --enable-xephyr in xorg.confopts) and did a very basic test:

$ /opt/X11/bin/Xephyr:4
$ DISPLAY=:4 xterm

It seemed fine ...  I'm going to use the new Xephyr in the next release . We can always roll back again if someone has an issue.
