### ISSUE TITLE
Compatibility version strings incorrect in libraries

### ISSUE THREAD

**Issue by james-vincent** [XQuartz/XQuartz#341]
Compatibility version strings reported by several libraries (libpixman example below) are set to 0.0.0 in XQuartz 2.8.3 and later. This breaks applications that depend on this string. Downgrading to 2.8.2 resolves the issue for those applications

```
libpixman
2.7.11 /opt/X11/lib/libpixman-1.0.dylib (compatibility version 41.0.0, current version 41.0.0)
2.8.1: /opt/X11/lib/libpixman-1.0.dylib (compatibility version 41.0.0, current version 41.0.0)
2.8.2: /opt/X11/lib/libpixman-1.0.dylib (compatibility version 41.0.0, current version 41.0.0)
2.8.3: /opt/X11/lib/libpixman-1.0.dylib (compatibility version 0.0.0, current version 0.0.0)
2.8.4: /opt/X11/lib/libpixman-1.0.dylib (compatibility version 0.0.0, current version 0.0.0)
2.8.5: /opt/X11/lib/libpixman-1.0.dylib (compatibility version 0.0.0, current version 0.0.0)
```

**Comment by jeremyhu** [comment]
Ugh.  Which other dylibs did you see this for?

**Comment by jeremyhu** [comment]
```
	/opt/X11/lib/libepoll-shim-interpose.0.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/X11/lib/libepoll-shim.0.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/X11/lib/libglapi.0.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/X11/lib/libpixman-1.0.dylib (compatibility version 0.0.0, current version 0.0.0)

```

**Comment by jeremyhu** [comment]
2.7.11 had:
```
	/opt/X11/lib/libglapi.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/opt/X11/lib/libpixman-1.0.dylib (compatibility version 35.0.0, current version 35.0.0)
```

**Comment by jeremyhu** [comment]
@james-vincent Can you double check... are you sure 2.7.11 had 41.0.0?  I see 35.0.0...

**Comment by jeremyhu** [comment]
We're in a bit of a pickle here...

Anything built against 2.7.x will work on 2.8.0-2.8.2 but not 2.8.3+.
Anything built against 2.8.0-2.8.2 won't work on 2.7.x nor 2.8.3+.
Anything built against the current (0.0.0) 0 version will actually run against all versions since the 0 in the client will indicate "don't enforce".

Thus if we bump it to 41.0, then we end up in a scenario where newer client binaries won't work with 2.8.3-2.8.5 (nor 2.7.x).

I think the best course of action here is to just leave it a 0 and ask clients to re-link against newer XQuartz ... 

I don't really see a better option.  If you have thoughts, I'd be happy to hear them...

Another option is to bump our required OS versiont o 10.14 since that would cause the system to completely ignore the enforcement...
