### ISSUE TITLE
font anti-alias

### ISSUE THREAD

**Issue by quantrpeter** [XQuartz/XQuartz#377]
hi.
   How to make the font support font anti-alias?
thanks
Peter

**Comment by dpeterc** [comment]
Strictly speaking, this question is not related to XQuartz.

Fonts are defined either in bitmap or vector form, and it is very hard turn them into vector form, if they are in bitmap format. Also, antialiasing must be supported by font rendering system, otherwise it is hard to do.
On X11 (and XQuartz is a MacOS implementation of X11), native fonts are either bitmap or vector, but without support for anti-aliased rendering.
https://www.x.org/wiki/guide/fonts/
But there is a newer additional library, called XFT, which supports anti-alised font rendering, and it is also part of XQuartz.
https://www.freedesktop.org/wiki/Software/Xft/
If you are programming your own applications, you can have a look here
https://keithp.com/~keithp/talks/xtc2001/paper/
If you are using a software developed by usage of relatively modern tookit, it is likely that the toolkit already supports XFT anti-aliased font rendering. Even the very old Motif software does it.
Here is an example of xmgrace graph plotting software running using xft anti-aliased fonts (and without on right)

![xmgraceXFT](https://github.com/XQuartz/XQuartz/assets/15419249/9cd641c3-dac1-4c2a-9cf3-5af219d57b4a)


In order to run it like this, use a command
`xmgrace -xrm "*renderTable: rt" -xrm "*rt*fontType: FONT_IS_XFT" -xrm "*rt*fontName: Sans" -xrm "*rt*fontSize: 10"
`

**Comment by quantrpeter** [comment]
thanks for your answer gentlemen
