### ISSUE TITLE
XQuartz 2.8.5 not working properly on macOS Sonoma 14.3, have to reinstall it after each reboot

### ISSUE THREAD

**Issue by anastasiyayilmaz** [XQuartz/XQuartz#388]
I've recently upgraded to macOS Sonoma 14.3 and updated XQuartz to the latest version. From the first moments after installation, trying to open a new xwindow session in Xspec stopped working. I would receive error messages like PGPLOT /xw: cannot connect to X server. After digging deep into almost everything I could think of, using "export DISPLAY=:0" seemed to work for a while. But now every time I rebook my laptop, I receive the same error. After rebooting, I can no longer even start the application manually. It starts bouncing on the dock but disappears immediately. I try to reinstall it and start the application manually, everything goes back to normal. But this started to happen in a loop every time I turned off my laptop and I had to reinstall it over and over.

I tried removing export DISPLAY=:0 from zshrc and then having a clean install but it goes back to giving the same error. Would appreciate any help to make it work!

**Comment by jeremyhu** [comment]
> I tried removing export DISPLAY=:0 from zshrc

Yes, absolutely do NOT set DISPLAY.  You should never ever ever need to do that.  Please don't.  Let the system set it for you.

---

As for why you have issues with that not present, you'll need to provide more information.  Most users get into this state because they turned off the relevant entries in System Preferences Login Items.
