### ISSUE TITLE
jumpy scrolling

### ISSUE THREAD

**Issue by elvis-the-king** [XQuartz/XQuartz#397]
I'm running XQuartz 2.8.5 (xorg-server 21.1.6) and the scrolling is very jumpy. The text gets blurred until the scrolling stops. Other apps not using X11 are fine when they scroll.

https://github.com/XQuartz/XQuartz/assets/98363967/582a8c4e-a5df-4222-a4f0-ec0e47c6d8de

**Comment by dpeterc** [comment]
Since a couple of years (from El Capitan 10.1), XQuartz became very sensitive (=slow) on poor X11 programming which requires a lot of round trips (X11 requests which require a reply from a server before continuing).
I have had this problem on Motif based application with XFT antialiased fonts (yours is also antialiased, but does not look like Motif toolkit). Problem was in the toolkit which asked background color (XQueryColor) from the  system every time it was drawing the label, since it needed background color for correct antialiased font rendering. When you scroll, this can result in thousands of quick redraws, and with slow round trip this can result in jerky movement like in your video.
Given that this regression in XQuartz was not resolved for many years, I think your best bet is to try to fix your toolkit. The solution was to cache the background color, since drawing text is relatively fast, but waiting for the result of background color value is slow.

Try disabling font antialiasing in your application, if scrolling will then become fast, then you have the same problem as I did. In my applications, the scrolling itself (which involves XCopyArea and refresh of newly exposed area) is not slow.

**Comment by elvis-the-king** [comment]
I don't know how to disable antialiasing. I tried doing it in the OS but it had no effect. I wrote the app using the Fox-toolkit (http://fox-toolkit.org/). I can change the font and have tried a few but they all have the same issue.

**Comment by dpeterc** [comment]
I have never used Fox toolkit, but I did a quick search.
Apparently XFT fonts can not be disabled in Fox toolkit, you need to try an older version which relies on X11 bitmap fonts.
I don't know if modern MacOS is still compatible with such old versions.
Maybe XFT antialiasing can be disabled also on XQuartz level (on older Linux this was possible with .Xresources with a line "Xft.antialias: false"), but I don't know how to do this.
https://sourceforge.net/p/foxgui/mailman/foxgui-users/thread/200409021815.30431.jeroen%40fox-toolkit.org/#msg15510694 
Maybe an alternative way of approaching the problem would be to create a minimum bug reproducer with source code and ask the question on fox toolkit forums; it appears to be a vivid community with lots of MacOS users.

**Comment by elvis-the-king** [comment]
There was an option in the Fox-toolkit to turn off smooth scrolling. This fixed it. Now it jumps 1 line at a time and there is no blurring.
