### ISSUE TITLE
"i386" binaries have remained in XQuartz 2.8.0_beta3

### ISSUE THREAD

**Issue by tkoba965** [XQuartz/XQuartz#65]
Please check the binaries:

<pre>
% find /opt/X11/lib -type f -name "*.dylib" | xargs file | grep i386
...
/opt/X11/lib/libcairo.2.dylib:                    Mach-O universal binary with 2 architectures: [i386:Mach-O dynamically linked shared library i386] [x86_64:Mach-O 64-bit dynamically linked shared library x86_64]
/opt/X11/lib/libcairo.2.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
...
/opt/X11/lib/libXplugin.1.dylib:                  Mach-O universal binary with 2 architectures: [i386:Mach-O dynamically linked shared library i386] [x86_64:Mach-O 64-bit dynamically linked shared library x86_64]
/opt/X11/lib/libXplugin.1.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
...
</pre>

**Comment by jeremyhu** [comment]
Yes, if you update from 2.7.x to 2.8.x, the additional libraries will be left on your system.  This is because we updated the package identifier, so they are not removed by the installer.  I decided not to remove them in a post-installation script to allow folks that need them to keep them in place.
