### ISSUE TITLE
Xquartz 'Could not create lock file in /tmp/.tX0-lock' infinite crash loop

### ISSUE THREAD

**Issue by emmaflan** [XQuartz/XQuartz#78]
Just installed XQuartz 2.8.0 beta3 on Big Sur and when opening from Terminal it crashes when launching in an infinite loop, giving the Application specific error 'Could not create lock file in /tmp/.tX0-lock'. I have checked tmp and can't find any file of this kind to delete it. Unable to find solution elsewhere, even though I have seen this error posted several times on different forums.

**Comment by jeremyhu** [comment]
Did you logout and log back in after doing the installation?

Assuming not, this is #52.

**Comment by emmaflan** [comment]
I did log in and log out after installation. I have also tried restarting and reinstalling the software several times with the same outcome. 

Interestingly, Xquartz started working after I did a software update (Big Sur 11.1), however reverted to the same crash loop when I started up my computer the next day.

**Comment by jeremyhu** [comment]
Are you permissions in /tmp correct?

You should see:

    $ ls -ald /private/tmp /tmp /tmp/.X11-unix 
    drwxrwxrwt 703 root wheel 22496 Feb 16 14:18 /private/tmp
    lrwxr-xr-x   1 root wheel    11 Jan  1  2020 /tmp -> private/tmp
    drwxrwxrwt   2 root wheel    64 Feb 16 11:58 /tmp/.X11-unix

**Comment by nelerey** [comment]
I think I have the same issue so will comment/add some info here instead of starting a new thread: XQuartz crashes in an infinite loop which can only be broken by logging out and back in again. (and I did log out and back in again every time I re-installed XQuartz while trying to solve this problem.) 
Currently this problem occurs on macbook pro with **macOS Catalina 10.15.7** and XQuartz **v2.8.0_rc2** , but it happened earlier with XQuartz **v2.7.11** as well. 

In the X11 crash report, it stated:
```
[...]
Application Specific Information:
X.Org X Server 1.19.7 Build Date: 20210226
**Could not create lock file in /tmp/.tX0-lock**
[...]
```

and the crash report looked almost the same as in this stackoverflow question describing this same issue (probably) on Mojave: https://stackoverflow.com/questions/61902886/xquartz-infinite-crash-and-restart-loop-mac-os-mojave 

At first, , my  ` ls -ald /private/tmp /tmp /tmp/.X11-unix` output looked like this:
```
drwxrwxr-x  31 root  wheel  992  1 Mar 18:50 /private/tmp
lrwxr-xr-x@  1 root  admin   11 31 May  2020 /tmp -> private/tmp
drwxrwxrwt   5 root  wheel  160  1 Mar 18:42 /tmp/.X11-unix
```

After running `chmod 777 /private/tmp`, my  ` ls -ald /private/tmp /tmp /tmp/.X11-unix` output now looks like this:
```
drwxrwxrwx  31 root  wheel  992  1 Mar 18:50 /private/tmp
lrwxr-xr-x@  1 root  admin   11 31 May  2020 /tmp -> private/tmp
drwxrwxrwt   5 root  wheel  160  1 Mar 18:42 /tmp/.X11-unix
```
(not sure if that @ would make a difference?) After this change, XQuartz doesn’t crash, but it does **still keep restarting when I try to (force) quit, and it doesn’t work when trying to use it to view graphics from a remote server connected through ssh.**

**Comment by jeremyhu** [comment]
> drwxrwxr-x  31 root  wheel  992  1 Mar 18:50 /private/tmp

That's definitely wrong!

> After running chmod 777 /private/tmp

Yeah, don't do that.

/private/tmp should have `drwxrwxrwt` ... ie: sudo chmod 1777 /private/tmp

You should figure out what caused your permissions to change on /private/tmp and fix that.
