### ISSUE TITLE
Window customizations no linger work XQuartz 2.7.11

### ISSUE THREAD

**Issue by Starman535** [XQuartz/XQuartz#80]
I tried XQuartz 2.8 Beta1 and 3 a few weeks ago, and it broke the customized window options I used (-sl 20000 -bg LightBlue -sb -geometry 120x55). I reverted to 2.7.11, but the customizations still do not work. I deleted the LaunchAgent, and that fixed IDLDE 8.8, but not the other. Any suggestions?

**Comment by jeremyhu** [comment]
What do you mean "it broke the customized window options"?  Where did you specify these options?  It is set in the Applications menu?  Assuming so, this is #49.

I'm not sure what you mean by "that fixed IDLDE 8.8", but the LaunchAgent issue should be resolved by #52 which forces the user to logout rather than just presenting a dialog that most folks click through and ignore.
