### ISSUE TITLE
XQuartz 2.8.0 incompatibility with IDL 8.5.1

### ISSUE THREAD

**Issue by giardiacorp** [XQuartz/XQuartz#95]
i am so thankful to everyone working on XQuartz, because it has been central to my being able to do science on a mac. nowadays everyone uses python, but i am old. 

**in IDL 8.5.1, commands that create Motif windows (e.g., dialog_pickfile() and xdisplayfile) instantly crash the IDL session under XQuartz 2.8.0. this happens with both the beta3 and the rc1 releases of XQuartz 2.8.0.**

IDL is used by a various science people, and it works great generally on a mac with X11. but it has an expensive license, so this could be a difficult bug for developers to track. i reported this issue to the L3harris geospatial (owners of IDL) support forum at https://www.l3harrisgeospatial.com/Support/Forums/aft/8476. my IDL version 8.5.1 is not even the current version, so it's possible that the issue is fixed for later versions. 

IDL used to have a separate issue that is very much improved in XQuartz 2.8.0: once you opened a graphic window, pasting text onto the IDL command line became painfully slow, like watching a dot matrix printer working (i told you i am old). but now it is much faster to paste text.

**Comment by jeremyhu** [comment]
What verison of motif are you using?  I wonder if it has the bug that was requiring the older flat-namespace version of libXt.

Can you please provide the crash log?

**Comment by jeremyhu** [comment]
Please also add a link to this bug report from that forum post, so others can find it.

**Comment by giardiacorp** [comment]
hi jeremy, i am unable to determine my motif version, i think it is just whatever comes with XQuartz. i am not an advanced sysadmin.

i also could not find a crash log, but i realized i overlooked these error messages output when IDL crashed:
```
Warning: Dialog style must be XmDIALOG_MODELESS.
Error: attempt to add non-widget child "dsm" to parent "idl" which supports only widgets

```
when i searched this online, i found a couple of links that confirm your hunch and solve this for a XQuartz 2.7.10: [[1]](https://blogs.qub.ac.uk/screenshotsfromtheedge/2016/10/25/xquartz-2-7-10-and-libxt-motif-idl/) [[2]](https://www.l3harrisgeospatial.com/Support/Self-Help-Tools/Help-Articles/Help-Articles-Detail/ArtMID/10220/ArticleID/15188/XQuartz-2710-is-Not-Compatible-with-ENVI-531-and-IDL-851). so i was able to use this workaround. presumably the more recent versions of IDL don't have this bug. maybe it is interesting that these pages report the issue for XQuartz 2.7.10, but i had no issue with XQuartz 2.7.11, just with XQuartz 2.8.0.

**Comment by jeremyhu** [comment]
XQuartz does not include Motif, so it's probably coming from IDL.  Motif uses libXt (which does come with XQuartz).  Motif had a bug (now fixed in current OpenMotif and Lesstif, I believe) that required libXt to be flat_namespace to work correctly.  flat_namespace has its own set of issues.

In 2.7.9, we made some changes:

   * Left libXt.6.dylib as flat-namespace
   * Built libXt.7.dylib as 2-level namespace

In 2.7.10, we then:

   * Made libXt.6.dylib 2-level namespace
   * Placed a re-export stub at libXt.7.dylib for clients who had rebuilt with XQuartz 2.7.9
   * Placed flat-namespace versions in a subdirectory (/opt/X11/lib/flat_namespace), so folks could still use them if they needed them.

I *suspect* that your IDL is trying to use the libs in  /opt/X11/lib/flat_namespace but not finding them (becasue we removed them).

I'm going to use this ticket to re-add those /opt/X11/lib/flat_namespace libraries.

**Comment by jeremyhu** [comment]
Can you please try 2.8.0_rc2?

**Comment by giardiacorp** [comment]
hi jeremy, thanks so much for looking into this.

IDL crashes with the same error. 

but as before, if i put /opt/X11/lib/flat_namespace in the DYLD_LIBRARY_PATH, then IDL functions fine in both 2.8.0_rc1 and 2.8.0_rc2. so after making the fix to change DYLD_LIBRARY_PATH, i am good to go. i'll post again if i find anything else amiss, but so far so good !!
